// app/layout.tsx
import {
  getAllShows,
  getAllProjects,
  getAllTeamMembers,
  getAllCommunityPosts,
  getAllLinks,
} from '@/app/sanity/client'
import NavComponent from './components/NavComponent'
import type { Metadata } from 'next'
import { Geist, Geist_Mono, Amatic_SC, Orbitron } from 'next/font/google'
import './globals.css'
import { Providers } from './providers'

// FONT THINGS

const amaticSc = Amatic_SC({
  variable: '--font-amatic-sc',
  weight: '700',
  subsets: ['latin'],
})

const orbitron = Orbitron({
  variable: '--font-orbitron',
  weight: 'variable',
  subsets: ['latin'],
})

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // Fetch all data for navigation
  const [shows, projects, teamMembers, communityPosts, links] =
    await Promise.all([
      getAllShows(),
      getAllProjects(),
      getAllTeamMembers(),
      getAllCommunityPosts(),
      getAllLinks(),
    ])

  const navData = {
    shows,
    projects,
    teamMembers,
    communityPosts,
    links,
  }

  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${amaticSc.variable} ${orbitron.variable}  antialiased`}
      >
        <Providers>
          <NavComponent data={navData} />

          {children}
        </Providers>
      </body>
    </html>
  )
}
